package com.loopbreak.entities;
// Generated Jun 11, 2017 10:04:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name="classes")
public class Classes implements java.io.Serializable {

	private Integer id;
	private String className;
	private String description;
	private Integer capacity;
	private Integer active;

	public Classes() {
	}

	public Classes(String className, String description, Integer capacity, Integer active) {
		this.className = className;
		this.description = description;
		this.capacity = capacity;
		this.active = active;
	}

	@Column
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Id
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Basic
	@Column(name="class_name")
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Basic
	@Column(name="description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(name="capacity")
	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	@Basic
	@Column(name="active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

}
