package com.loopbreak.entities;
// Generated Jun 11, 2017 10:04:11 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExamRoutine generated by hbm2java
 */
@Entity
@Table(name = "eam_routine")
public class ExamRoutine implements java.io.Serializable {

	private Integer id;
	private Integer subjectId;
	private Integer roomtId;
	private Date timeStart;
	private Date timeEnd;
	private Integer active;

	public ExamRoutine() {
	}

	public ExamRoutine(Integer subjectId, Integer roomtId, Date timeStart, Date timeEnd, Integer active) {
		this.subjectId = subjectId;
		this.roomtId = roomtId;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.active = active;
	}

	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Basic
	@Column(name = "subject_id")
	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	@Basic
	@Column(name = "room_id")
	public Integer getRoomtId() {
		return this.roomtId;
	}

	public void setRoomtId(Integer roomtId) {
		this.roomtId = roomtId;
	}

	@Basic
	@Column(name = "time_start")
	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	@Basic
	@Column(name = "time_end")
	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	@Basic
	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

}
