package com.loopbreak.entities;
// Generated Jun 11, 2017 10:04:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExamResult generated by hbm2java
 */
@Entity
@Table(name = "eam_result")
public class ExamResult implements java.io.Serializable {

	private Integer id;
	private Integer examId;
	private Integer studentId;
	private Integer subjectId;
	private Integer totalMarks;
	private Integer passMarks;
	private Integer obtainedMarks;
	private Integer grade;
	private Integer active;

	public ExamResult() {
	}

	public ExamResult(Integer examId, Integer studentId, Integer subjectId, Integer totalMarks, Integer passMarks,
			Integer obtainedMarks, Integer grade, Integer active) {
		this.examId = examId;
		this.studentId = studentId;
		this.subjectId = subjectId;
		this.totalMarks = totalMarks;
		this.passMarks = passMarks;
		this.obtainedMarks = obtainedMarks;
		this.grade = grade;
		this.active = active;
	}

	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Basic
	@Column(name = "exam_id")
	public Integer getExamId() {
		return this.examId;
	}

	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	@Basic
	@Column(name = "student_id")
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@Basic
	@Column(name = "subject_id")
	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	@Basic
	@Column(name = "total_marks")
	public Integer getTotalMarks() {
		return this.totalMarks;
	}

	public void setTotalMarks(Integer totalMarks) {
		this.totalMarks = totalMarks;
	}

	@Basic
	@Column(name = "pass_marks")
	public Integer getPassMarks() {
		return this.passMarks;
	}

	public void setPassMarks(Integer passMarks) {
		this.passMarks = passMarks;
	}

	@Basic
	@Column(name = "obtained_marks")
	public Integer getObtainedMarks() {
		return this.obtainedMarks;
	}

	public void setObtainedMarks(Integer obtainedMarks) {
		this.obtainedMarks = obtainedMarks;
	}

	@Basic
	@Column(name = "grade")
	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	@Basic
	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

}
