package com.loopbreak.entities;
// Generated Jun 11, 2017 10:04:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Files generated by hbm2java
 */
@Entity
@Table(name = "files")
public class Files implements java.io.Serializable {

	private Integer id;
	private String filePath;
	private Integer active;
	private Integer uploadedBy;

	public Files() {
	}

	public Files(String filePath, Integer active, Integer uploadedBy) {
		this.filePath = filePath;
		this.active = active;
		this.uploadedBy = uploadedBy;
	}

	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="file_path")
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name="uploaded_by")
	public Integer getUploadedBy() {
		return this.uploadedBy;
	}

	public void setUploadedBy(Integer uploadedBy) {
		this.uploadedBy = uploadedBy;
	}

}
