package com.loopbreak.entities;
// Generated Jun 11, 2017 10:04:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gallary generated by hbm2java
 */
@Entity
@Table(name="gallary")
public class Gallary implements java.io.Serializable {

	private Integer id;
	private Integer imagePath;
	private String title;
	private String description;
	private String active;
	private String imageCredit;

	public Gallary() {
	}

	public Gallary(Integer imagePath, String title, String description, String active, String imageCredit) {
		this.imagePath = imagePath;
		this.title = title;
		this.description = description;
		this.active = active;
		this.imageCredit = imageCredit;
	}

	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="image_path")
	public Integer getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(Integer imagePath) {
		this.imagePath = imagePath;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name="image_credit")
	public String getImageCredit() {
		return this.imageCredit;
	}

	public void setImageCredit(String imageCredit) {
		this.imageCredit = imageCredit;
	}

}
