package com.loopbreak.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated Jun 11, 2017 10:04:11 PM by Hibernate Tools 5.2.1.Final

/**
 * NoticeFileRole generated by hbm2java
 */
@Entity
@Table(name="notice_file_role")
public class NoticeFileRole implements java.io.Serializable {

	private Integer id;
	private Integer fileId;
	private Integer noticeId;
	private Integer active;

	public NoticeFileRole() {
	}

	public NoticeFileRole(Integer fileId, Integer noticeId, Integer active) {
		this.fileId = fileId;
		this.noticeId = noticeId;
		this.active = active;
	}
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="file_id")
	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	@Column(name="notice_id")
	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

}
