package com.loopbreak.entities;
// Generated Jun 11, 2017 10:04:11 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentPayments generated by hbm2java
 */
@Entity
@Table(name = "student_payments")
public class StudentPayments implements java.io.Serializable {

	private Integer id;
	private Integer classId;
	private Integer studentId;
	private Double amount;
	private Double paid;
	private Double due;
	private Double fine;
	private Integer active;
	private Date createdAt;
	private Date updatedAt;
	private Integer feesId;

	public StudentPayments() {
	}

	public StudentPayments(Integer classId, Integer studentId, Double amount, Double paid, Double due, Double fine,
			Integer active, Date createdAt, Date updatedAt, Integer feesId) {
		this.classId = classId;
		this.studentId = studentId;
		this.amount = amount;
		this.paid = paid;
		this.due = due;
		this.fine = fine;
		this.active = active;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.feesId = feesId;
	}

	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "class_id")
	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	@Column(name = "student_id")
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public Double getPaid() {
		return this.paid;
	}

	public void setPaid(Double paid) {
		this.paid = paid;
	}

	public Double getDue() {
		return this.due;
	}

	public void setDue(Double due) {
		this.due = due;
	}

	public Double getFine() {
		return this.fine;
	}

	public void setFine(Double fine) {
		this.fine = fine;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "created_at")
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "updated_at")
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Integer getFeesId() {
		return this.feesId;
	}

	public void setFeesId(Integer feesId) {
		this.feesId = feesId;
	}

}
