package com.loopbreak.entities;
// Generated Jun 11, 2017 10:04:11 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentStatus generated by hbm2java
 */
@Entity
@Table(name = "student_status")
public class StudentStatus implements java.io.Serializable {

	private Integer id;
	private String name;
	private String displayName;
	private Integer active;
	private Integer createdAt;
	private Integer updatedAt;

	public StudentStatus() {
	}

	public StudentStatus(String name, String displayName, Integer active, Integer createdAt, Integer updatedAt) {
		this.name = name;
		this.displayName = displayName;
		this.active = active;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "created_at")
	public Integer getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Integer createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "updated_at")
	public Integer getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Integer updatedAt) {
		this.updatedAt = updatedAt;
	}

}
