package com.loopbreak.entities;
// Generated Jun 11, 2017 10:04:11 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vacations generated by hbm2java
 */
@Entity
@Table(name="vacations")
public class Vacations implements java.io.Serializable {

	private Integer id;
	private String title;
	private String description;
	private Date dayStart;
	private Date dayEnd;
	private Integer totalDays;
	private Integer updatedBy;
	private Integer active;

	public Vacations() {
	}

	public Vacations(String title, String description, Date dayStart, Date dayEnd, Integer totalDays, Integer updatedBy,
			Integer active) {
		this.title = title;
		this.description = description;
		this.dayStart = dayStart;
		this.dayEnd = dayEnd;
		this.totalDays = totalDays;
		this.updatedBy = updatedBy;
		this.active = active;
	}
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name="day_start")
	public Date getDayStart() {
		return this.dayStart;
	}

	public void setDayStart(Date dayStart) {
		this.dayStart = dayStart;
	}
	@Column(name="day_end")
	public Date getDayEnd() {
		return this.dayEnd;
	}

	public void setDayEnd(Date dayEnd) {
		this.dayEnd = dayEnd;
	}
	@Column(name="total_days")
	public Integer getTotalDays() {
		return this.totalDays;
	}

	public void setTotalDays(Integer totalDays) {
		this.totalDays = totalDays;
	}
	@Column(name="updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

}
